{% set name = "cdp" %}
{% set version = "1.5.1" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/cdp/archive/v{{ version }}.tar.gz
  sha256: 78b15a9e1d0d9afc55acdb20770faab3e110aba5edadef31a56f957465fc10c3

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    entry_points:
      - cdp-distrib = cdp.cli.cdp_distrib:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - output_viewer >=1.3.0
    - pyyaml
    - dask
    - distributed
    - six

test:
  imports:
      - cdp
  commands:
      - cdp-distrib -h

about:
  home: https://github.com/cdat/cdp
  summary: |
    The Community Diagnostics Package (CDP) is a framework for developing new
    climate diagnostics. CDP allows for a modular implementation of the
    components required for running diagnostics. The design of CDP consists
    of modules to handle the user-defined parameters, metrics, provenance,
    file I/O, output of results and algorithms for calculating the diagnostics.
  license: BSD-3-Clause
  license_file: bsd-3-clause.txt

extra:
    recipe-maintainers:
        - doutriaux1
        - zshaheen
        - xylar
