travis:
  secure:
    BINSTAR_TOKEN: iaNAxX0tZim0wXTtYQT2nXq0aI4Y2VrPtFfgS34wsPwNbNyH77Y89eFmiPDBYuLrmHUuxJYF+mPhLZKojUM1IAdFmTKzY4lWg4bnXTYjVSYhNcvNuOqjWXrBtBBdbZa3fg7pO4QgUpBjh5kZHVdmRyiozujXwqNGAGianooPiY8vFvDlyE9SU9abDWl9tyLZmj2ZvoMFdYXZi4CXjUTA9lbDvjQupYJHY95TfjvWObVHjDSO2NfMe4QaIbMinNzYMSK9GsHAs8PI7RMfPAlTBC/H9cTxjJ9usHXQ6IhfFbjLIiY+L3zFvmeO8yzcp1UAVvkWLrqvCavLYMO/wfTj/FFe9KciqMx40KANFGj1b1LJ7v2j5R28g83Qq6mMqzsn4WLIL3cQh4xBY1sX1c7GUV1ns0VpSqrH4ChVWgjYBc3/dI8mMr532xo37OixRoxrMKrXFrr50PNJQPPm7Q/EoCOYiYBjKybWFnuSECX8hwIxOmEnHpVlcAlTQ1N2WUC9orrWJDGoFZwLNrphFmbexGZ1ELJ2K11KvcUpf1hsVJ/jpMTNEGODYfwfCivx2crEMhl50gmNpjFiSeNUBsrbFqAfD0OJ8jbXNieSiBkP8KCR503zQNNsfPqB3zk0xX+QktUkcdrCyH7Gp1bRg4NKOOltT/itmdEIGDAFYGSQf3A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
